apiVersion: v1
kind: Secret
metadata:
  name: demo-todo-secret
  namespace: demo-todo
  annotations:
    avp.kubernetes.io/path: "secret/data/demo-todo"
type: Opaque
stringData:
  DATABASE_URL: "db#DATABASE_URL>"
  TELEGRAM_BOT_TOKEN: "tg#TELEGRAM_BOT_TOKEN>"
  TELEGRAM_CHAT_ID: "tg#TELEGRAM_CHAT_ID>"