apiVersion: v1
kind: Service
metadata:
  name: demo-todo-svc
  labels:
    app: demo-todo-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: demo-todo-app
